export const seedHospitals = [
    {
        name: 'AIIMS Blood Bank',
        type: 'blood_bank',
        address: 'Ansari Nagar, AIIMS Campus',
        city: 'New Delhi',
        state: 'Delhi',
        pincode: '110029',
        phone: '011-26588500',
        emergencyPhone: '011-26593308',
        email: 'bloodbank@aiims.edu',
        website: 'https://www.aiims.edu',
        bloodGroupsAvailable: ['A+', 'A-', 'B+', 'B-', 'AB+', 'AB-', 'O+', 'O-'],
        is24x7: true,
        notes: 'One of the largest blood banks in India. Walk-in donation welcome.',
    },
    {
        name: 'Red Cross Society Blood Bank',
        type: 'blood_bank',
        address: 'Red Cross Bhawan, 1 Red Cross Road',
        city: 'New Delhi',
        state: 'Delhi',
        pincode: '110001',
        phone: '011-23716441',
        emergencyPhone: '011-23716431',
        email: 'delhi@indianredcross.org',
        website: 'https://indianredcross.org',
        bloodGroupsAvailable: ['A+', 'B+', 'AB+', 'O+', 'O-'],
        is24x7: true,
    },
    {
        name: 'Apollo Hospital Blood Bank',
        type: 'hospital',
        address: 'Sarita Vihar, Delhi-Mathura Road',
        city: 'New Delhi',
        state: 'Delhi',
        pincode: '110076',
        phone: '011-26925858',
        emergencyPhone: '1066',
        website: 'https://www.apollohospitals.com',
        bloodGroupsAvailable: ['A+', 'A-', 'B+', 'B-', 'AB+', 'AB-', 'O+', 'O-'],
        is24x7: true,
        notes: 'Component separation facility. Free hepatitis screening.',
    },
    {
        name: 'Tata Memorial Blood Bank',
        type: 'blood_bank',
        address: 'Dr. E Borges Road, Parel',
        city: 'Mumbai',
        state: 'Maharashtra',
        pincode: '400012',
        phone: '022-24177000',
        email: 'bloodbank@tmc.gov.in',
        bloodGroupsAvailable: ['A+', 'B+', 'AB+', 'O+', 'O-', 'A-', 'B-'],
        is24x7: false,
        notes: 'Open Mon–Sat, 9 AM to 5 PM. Cancer patient priority.',
    },
    {
        name: 'KEM Hospital Blood Bank',
        type: 'hospital',
        address: 'Acharya Donde Marg, Parel',
        city: 'Mumbai',
        state: 'Maharashtra',
        pincode: '400012',
        phone: '022-24107000',
        emergencyPhone: '022-24107777',
        bloodGroupsAvailable: ['A+', 'A-', 'B+', 'B-', 'AB+', 'AB-', 'O+', 'O-'],
        is24x7: true,
    },
    {
        name: 'NIMHANS Blood Bank',
        type: 'blood_bank',
        address: 'Hosur Road',
        city: 'Bangalore',
        state: 'Karnataka',
        pincode: '560029',
        phone: '080-26995001',
        bloodGroupsAvailable: ['A+', 'B+', 'AB+', 'O+', 'O-'],
        is24x7: false,
    },
    {
        name: 'Manipal Hospital Blood Bank',
        type: 'hospital',
        address: '98, HAL Old Airport Road',
        city: 'Bangalore',
        state: 'Karnataka',
        pincode: '560017',
        phone: '080-25024444',
        emergencyPhone: '1800-102-1408',
        website: 'https://www.manipalhospitals.com',
        bloodGroupsAvailable: ['A+', 'A-', 'B+', 'B-', 'AB+', 'AB-', 'O+', 'O-'],
        is24x7: true,
    },
];
